apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl-pod # Base POD name
spec:
  selector:
    matchLabels:
      app: shorturl-api # Selector for POD name search.
  template:
    metadata:
      labels:
        app: shorturl-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        # shorturl-api container configuration
        - name: shorturl-api
          image: shorturl-api-amd64:1.0
          ports:
            - name: shorturl-api
              containerPort: 3000
            - name: surl-api-debug
              containerPort: 4000
          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          env:
            - name: SHORTURL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: shorturl-service
spec:
  type: ClusterIP
  selector:
    service: shorturl-api
  ports:
    - name: shorturl-api
      port: 3000
      targetPort: shorturl-api
    - name: surl-api-debug
      port: 4000
      targetPort: surl-api-debug
